# Generated by Django 5.1.6 on 2025-03-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
